# Generated by Django 4.0.1 on 2022-03-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreenode',
            name='pigeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigeons', to='omni.pigeon'),
        ),
    ]
