# Generated by Django 4.0.1 on 2022-03-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0005_alter_pigeon_pedigreenodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigeon',
            name='pedigreeNodes',
        ),
        migrations.AddField(
            model_name='pedigreenode',
            name='pigeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pigeon', to='omni.pigeon'),
        ),
    ]
