# Generated by Django 4.0.1 on 2022-03-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0006_remove_pigeon_pedigreenodes_pedigreenode_pigeon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigreenode',
            name='pigeon',
        ),
    ]
