# Generated by Django 4.0.1 on 2022-03-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0007_remove_pedigreenode_pigeon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreenode',
            name='pigeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pigeon', to='omni.pigeon'),
        ),
    ]
