# Generated by Django 4.0.1 on 2022-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0010_alter_pedigreenode_noeudid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='pedigreeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='pigeonId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
