# Generated by Django 4.0.1 on 2022-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0011_alter_pedigree_pedigreeid_alter_pigeon_pigeonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreenode',
            name='isRoot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
