# Generated by Django 4.0.1 on 2022-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0012_pedigreenode_isroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='flagPigeon',
            field=models.BooleanField(default=True),
        ),
    ]
