# Generated by Django 4.0.1 on 2022-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0013_pigeon_flagpigeon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='flagPedigree',
            field=models.BooleanField(default=True),
        ),
    ]
