# Generated by Django 4.0.1 on 2022-04-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0014_pedigree_flagpedigree'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutPedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='filetest',
        ),
        migrations.AddField(
            model_name='pedigree',
            name='statut',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='omni.statutpedigree'),
        ),
    ]
